### ISSUE TITLE
EnhancedExpBar causing TypeloadException

### ISSUE THREAD

**Issue by 53m1k0l0n** [Haselnussbomber/HaselTweaks#29]
[dalamud.log](https://github.com/Haselnussbomber/HaselTweaks/files/10581239/dalamud.log)

2023-02-03 18:24:11.669 +01:00 [ERR] Exception during raise of Void <InvokeSafely>b__0()
System.TypeLoadException: Could not load type 'FFXIVClientStructs.FFXIV.Client.Game.MJIManager' from assembly 'FFXIVClientStructs, Version=1.0.0.1705, Culture=neutral, PublicKeyToken=null'.
   at HaselTweaks.Tweaks.EnhancedExpBar.OnFrameworkUpdate(Framework framework)
   at HaselTweaks.Plugin.OnFrameworkUpdate(Framework framework) in /_/Plugin.cs:line 102
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96

**Comment by Haselnussbomber** [comment]
Yep, already known (#28).
Change in Client Structs on staging Dalamud. Has to be on stable for now.
Alternatively, since I don't have testing releases, you can download the [artifact](https://github.com/Haselnussbomber/HaselTweaks/actions/runs/4079820626) and replace the files in `%APPDATA%\XIVLauncher\installedPlugins\HeelsPlugin\1.3.2`.

**Comment by Haselnussbomber** [comment]
Whops, wrong path (brain afk during hunts^^). Fixed the comment.

**Comment by Haselnussbomber** [comment]
The ClientStructs changes landed on stable, so I released [v0.9.5](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.9.5) to fix the crash.
