### ISSUE TITLE
Crash with auto open recipe tweak recently?

### ISSUE THREAD

**Issue by Dedoooo** [Haselnussbomber/HaselTweaks#40]
this only started happening yesterday and today, specific beast tribe quests i've noticed that have their quest text similar to some recipes crash the game Ex. certain kobold quest that contains the word "crate" i believe.

looked into the dalamud log and found this at everytime i've crashed at a beast tribe that contained similar crafting quest objective lines about 3 times:
t System.Environment.get_StackTrace()

   at Dalamud.EntryPoint.VehCallback() in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 70

   at FFXIVClientStructs.FFXIV.Client.Game.Event.EventFramework.GetEventHandlerById(UInt32 id) in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIVClientStructs.InteropSourceGenerators\FFXIVClientStructs.InteropSourceGenerators.MemberFunctionGenerator\FFXIVClientStructs.FFXIV.Client.Game.Event.EventFramework.MemberFunctions.g.cs:line 65

   at HaselTweaks.Tweaks.AutoOpenRecipe.UpdateQuestWork(UInt16 index, IntPtr questData, Boolean a3, Boolean a4, Boolean a5) in /_/Tweaks/AutoOpenRecipe.cs:line 157

   at Dalamud.Game.Network.GameNetwork.ProcessZonePacketDownDetour(IntPtr a, UInt32 targetId, IntPtr dataPtr) in C:\goatsoft\companysecrets\dalamud\Game\Network\GameNetwork.cs:line 102

   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 487
   
  --
   if this doesn't give you a clue at whats wrong or it only happens to me i can do more testing to make sure, but the quest objective and the dalamud log makes me think it's the culprit

i heard there were some changes with dalamud staging so perhaps its that instead, i'm not really sure.

**Comment by Haselnussbomber** [comment]
Oh! Yeah, I know exactly what it is.
I moved the `EventFramework.Instance()` call into the Setup function of the tweak, so it only resolves it once. Seems like the address changes, because the game creates a new EventFramework on login or something.
I'll change it back, and probably for the others too - just to be safe. It really makes no difference in the end.

**Comment by Haselnussbomber** [comment]
I've released [v0.13.5](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.13.5) which should fix it. 🙂
