### ISSUE TITLE
[Bug] Gear Set Grid

### ISSUE THREAD

**Issue by SayuShira** [Haselnussbomber/HaselTweaks#58]
Saw this tweak yesterday. It's a neat thing to see if something wasn't synced yet.

Wanted to let you know, that I encountered an issue tho. When I open it, it cut off in entry 17 (see image).

I have 32 sets. All my crafters have the same gear, so leatherworkers should have it filled too.
The tooltips know about the other gear sets.

![image](https://github.com/Haselnussbomber/HaselTweaks/assets/104025906/4682bd0e-6393-4f65-9ee2-48e9c248519f)
![image](https://github.com/Haselnussbomber/HaselTweaks/assets/104025906/448af48d-659f-4acd-b8d4-b053b462b224)

My gearsets ingame:
![image](https://github.com/Haselnussbomber/HaselTweaks/assets/104025906/18fde688-d998-4a14-aca3-4914388e8b62)

**Comment by Haselnussbomber** [comment]
Yeah, I had this happen once in development. It's throwing an error and that's why it cuts off.
Sadly I didn't save my `dalamud.log`, so I don't know what it was and it didn't occur again after I zoned out. 😕

It's on my radar for sure!

**Comment by SayuShira** [comment]
```19:33:21.787 | ERR [HaselTweaks] Unexpected exception in OnDraw
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HaselTweaks.Utils.Colors.GetItemLevelColor(Byte classJob, Item item, Vector4[] colors) in /_/Utils/ImGui/Colors.cs:line 49
   at HaselTweaks.Windows.GearSetGridWindow.Draw() in /_/Windows/GearSetGridWindow.cs:line 241
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 308
   at Dalamud.Interface.Windowing.WindowSystem.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\WindowSystem.cs:line 152
   at HaselTweaks.Plugin.OnDraw() in /_/Plugin.cs:line 142
{ } [ Send ]
```

This is the error I get in /xldev's Console log. It repeats a thousand times in dalamud.log, too.

**Comment by Haselnussbomber** [comment]
Yep, I just found out why! :joy: Fix underway. 🙂

**Comment by Haselnussbomber** [comment]
Alright, [v16.0.3](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v16.0.3) should fix this. I'll close this issue now, but if there are still problems don't hesitate to comment.
Thank you! 😃
