### ISSUE TITLE
No versions of HaselTweaks loading

### ISSUE THREAD

**Issue by jmrs2603** [Haselnussbomber/HaselTweaks#9]
Dalamud refuses to load any version of HaselTweaks, from the custom repo or via manual installation.

**Comment by Haselnussbomber** [comment]
Hmm, I just tried it with a completly empty `AppData\Roaming\XIVLauncher` folder, so everything starts over from fresh.
I added my repository, installed my plugin and had no problems at all. The Plugin loaded just fine.
Maybe you can find something in your `dalamud.log`.

**Comment by jmrs2603** [comment]
2022-08-10 00:06:46.264 +01:00 [INF] [PLUGINM] Installed plugin HaselTweaks (testing=False)
2022-08-10 00:06:46.264 +01:00 [INF] [PLUGINM] Loading plugin HaselTweaks
2022-08-10 00:06:46.274 +01:00 [INF] [LOCALPLUGIN] Loading HaselTweaks.dll
2022-08-10 00:06:46.528 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0xMFQwMDowNjo0Ni41Mjg1NjE2KzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBOZXd0b25zb2Z0Lkpzb24uSnNvblJlYWRlckV4Y2VwdGlvbjogRXJyb3IgcmVhZGluZyBKT2JqZWN0IGZyb20gSnNvblJlYWRlci4gUGF0aCAnJywgbGluZSAxLCBwb3NpdGlvbiAxOTQ2LlxyXG4gICBhdCBOZXd0b25zb2Z0Lkpzb24uTGlucS5KT2JqZWN0LkxvYWQoSnNvblJlYWRlciByZWFkZXIsIEpzb25Mb2FkU2V0dGluZ3Mgc2V0dGluZ3MpXHJcbiAgIGF0IE5ld3RvbnNvZnQuSnNvbi5MaW5xLkpPYmplY3QuUGFyc2UoU3RyaW5nIGpzb24sIEpzb25Mb2FkU2V0dGluZ3Mgc2V0dGluZ3MpXHJcbiAgIGF0IEhhc2VsVHdlYWtzLkNvbmZpZ3VyYXRpb24uTG9hZChTdHJpbmdbXSB0d2Vha05hbWVzKSBpbiAvaG9tZS9ydW5uZXIvd29yay9IYXNlbFR3ZWFrcy9IYXNlbFR3ZWFrcy9Db25maWd1cmF0aW9uLmNzOmxpbmUgNDRcclxuICAgYXQgSGFzZWxUd2Vha3MuUGx1Z2luLi5jdG9yKERhbGFtdWRQbHVnaW5JbnRlcmZhY2UgcGx1Z2luSW50ZXJmYWNlKSBpbiAvaG9tZS9ydW5uZXIvd29yay9IYXNlbFR3ZWFrcy9IYXNlbFR3ZWFrcy9QbHVnaW4uY3M6bGluZSA0NVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlJ1bnRpbWVNZXRob2RIYW5kbGUuSW52b2tlTWV0aG9kKE9iamVjdCB0YXJnZXQsIE9iamVjdFtdIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBjb25zdHJ1Y3RvciwgQm9vbGVhbiB3cmFwRXhjZXB0aW9ucylcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZUNvbnN0cnVjdG9ySW5mby5JbnZva2UoT2JqZWN0IG9iaiwgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIsIEJpbmRlciBiaW5kZXIsIE9iamVjdFtdIHBhcmFtZXRlcnMsIEN1bHR1cmVJbmZvIGN1bHR1cmUpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLk1ldGhvZEJhc2UuSW52b2tlKE9iamVjdCBvYmosIE9iamVjdFtdIHBhcmFtZXRlcnMpXHJcbiAgIGF0IERhbGFtdWQuSW9DLkludGVybmFsLlNlcnZpY2VDb250YWluZXIuQ3JlYXRlQXN5bmMoVHlwZSBvYmplY3RUeXBlLCBPYmplY3RbXSBzY29wZWRPYmplY3RzKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJb0NcXEludGVybmFsXFxTZXJ2aWNlQ29udGFpbmVyLmNzOmxpbmUgMTA0XHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlR5cGVzLkxvY2FsUGx1Z2luLkxvYWRBc3luYyhQbHVnaW5Mb2FkUmVhc29uIHJlYXNvbiwgQm9vbGVhbiByZWxvYWRpbmcpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFR5cGVzXFxMb2NhbFBsdWdpbi5jczpsaW5lIDQxNCIsIkNvbnRleHQiOiJbTE9DQUxQTFVHSU5dIEVycm9yIHdoaWxlIGxvYWRpbmcgSGFzZWxUd2Vha3MifQ==
2022-08-10 00:06:46.528 +01:00 [ERR] [LOCALPLUGIN] Error while loading HaselTweaks
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 1946.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at HaselTweaks.Configuration.Load(String[] tweakNames) in /home/runner/work/HaselTweaks/HaselTweaks/Configuration.cs:line 44
   at HaselTweaks.Plugin..ctor(DalamudPluginInterface pluginInterface) in /home/runner/work/HaselTweaks/HaselTweaks/Plugin.cs:line 45
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 414
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 746
2022-08-10 00:06:46.529 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0xMFQwMDowNjo0Ni41MjkzNzUrMDE6MDAiLCJJbmZvIjoiU3lzdGVtLlJlZmxlY3Rpb24uVGFyZ2V0SW52b2NhdGlvbkV4Y2VwdGlvbjogRXhjZXB0aW9uIGhhcyBiZWVuIHRocm93biBieSB0aGUgdGFyZ2V0IG9mIGFuIGludm9jYXRpb24uXHJcbiAtLS0+IE5ld3RvbnNvZnQuSnNvbi5Kc29uUmVhZGVyRXhjZXB0aW9uOiBFcnJvciByZWFkaW5nIEpPYmplY3QgZnJvbSBKc29uUmVhZGVyLiBQYXRoICcnLCBsaW5lIDEsIHBvc2l0aW9uIDE5NDYuXHJcbiAgIGF0IE5ld3RvbnNvZnQuSnNvbi5MaW5xLkpPYmplY3QuTG9hZChKc29uUmVhZGVyIHJlYWRlciwgSnNvbkxvYWRTZXR0aW5ncyBzZXR0aW5ncylcclxuICAgYXQgTmV3dG9uc29mdC5Kc29uLkxpbnEuSk9iamVjdC5QYXJzZShTdHJpbmcganNvbiwgSnNvbkxvYWRTZXR0aW5ncyBzZXR0aW5ncylcclxuICAgYXQgSGFzZWxUd2Vha3MuQ29uZmlndXJhdGlvbi5Mb2FkKFN0cmluZ1tdIHR3ZWFrTmFtZXMpIGluIC9ob21lL3J1bm5lci93b3JrL0hhc2VsVHdlYWtzL0hhc2VsVHdlYWtzL0NvbmZpZ3VyYXRpb24uY3M6bGluZSA0NFxyXG4gICBhdCBIYXNlbFR3ZWFrcy5QbHVnaW4uLmN0b3IoRGFsYW11ZFBsdWdpbkludGVyZmFjZSBwbHVnaW5JbnRlcmZhY2UpIGluIC9ob21lL3J1bm5lci93b3JrL0hhc2VsVHdlYWtzL0hhc2VsVHdlYWtzL1BsdWdpbi5jczpsaW5lIDQ1XHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZU1ldGhvZEhhbmRsZS5JbnZva2VNZXRob2QoT2JqZWN0IHRhcmdldCwgT2JqZWN0W10gYXJndW1lbnRzLCBTaWduYXR1cmUgc2lnLCBCb29sZWFuIGNvbnN0cnVjdG9yLCBCb29sZWFuIHdyYXBFeGNlcHRpb25zKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5SdW50aW1lQ29uc3RydWN0b3JJbmZvLkludm9rZShPYmplY3Qgb2JqLCBCaW5kaW5nRmxhZ3MgaW52b2tlQXR0ciwgQmluZGVyIGJpbmRlciwgT2JqZWN0W10gcGFyYW1ldGVycywgQ3VsdHVyZUluZm8gY3VsdHVyZSlcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uTWV0aG9kQmFzZS5JbnZva2UoT2JqZWN0IG9iaiwgT2JqZWN0W10gcGFyYW1ldGVycylcclxuICAgYXQgRGFsYW11ZC5Jb0MuSW50ZXJuYWwuU2VydmljZUNvbnRhaW5lci5DcmVhdGVBc3luYyhUeXBlIG9iamVjdFR5cGUsIE9iamVjdFtdIHNjb3BlZE9iamVjdHMpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXElvQ1xcSW50ZXJuYWxcXFNlcnZpY2VDb250YWluZXIuY3M6bGluZSAxMDRcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuVHlwZXMuTG9jYWxQbHVnaW4uTG9hZEFzeW5jKFBsdWdpbkxvYWRSZWFzb24gcmVhc29uLCBCb29sZWFuIHJlbG9hZGluZykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcVHlwZXNcXExvY2FsUGx1Z2luLmNzOmxpbmUgNDE0XHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlBsdWdpbk1hbmFnZXIuTG9hZFBsdWdpbkFzeW5jKEZpbGVJbmZvIGRsbEZpbGUsIExvY2FsUGx1Z2luTWFuaWZlc3QgbWFuaWZlc3QsIFBsdWdpbkxvYWRSZWFzb24gcmVhc29uLCBCb29sZWFuIGlzRGV2LCBCb29sZWFuIGlzQm9vdCwgQm9vbGVhbiBkb05vdExvYWQpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFBsdWdpbk1hbmFnZXIuY3M6bGluZSA3NDZcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuUGx1Z2luTWFuYWdlci5JbnN0YWxsUGx1Z2luQXN5bmMoUmVtb3RlUGx1Z2luTWFuaWZlc3QgcmVwb01hbmlmZXN0LCBCb29sZWFuIHVzZVRlc3RpbmcsIFBsdWdpbkxvYWRSZWFzb24gcmVhc29uKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxQbHVnaW5NYW5hZ2VyLmNzOmxpbmUgNjk5IiwiQ29udGV4dCI6IltQTFVHSU5XXSBQbHVnaW4gaW5zdGFsbGVyIHRocmV3IGFuIHVuZXhwZWN0ZWQgZXJyb3IifQ==
2022-08-10 00:06:46.529 +01:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 1946.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at HaselTweaks.Configuration.Load(String[] tweakNames) in /home/runner/work/HaselTweaks/HaselTweaks/Configuration.cs:line 44
   at HaselTweaks.Plugin..ctor(DalamudPluginInterface pluginInterface) in /home/runner/work/HaselTweaks/HaselTweaks/Plugin.cs:line 45
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 414
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 746
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 699
2022-08-10 00:06:54.357 +01:00 [INF] [PLUGINM] Installed plugin HaselTweaks (testing=False)
2022-08-10 00:06:54.357 +01:00 [INF] [PLUGINM] Loading plugin HaselTweaks
2022-08-10 00:06:54.364 +01:00 [INF] [LOCALPLUGIN] Loading HaselTweaks.dll
2022-08-10 00:06:54.590 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0xMFQwMDowNjo1NC41OTAwNDQ2KzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBOZXd0b25zb2Z0Lkpzb24uSnNvblJlYWRlckV4Y2VwdGlvbjogRXJyb3IgcmVhZGluZyBKT2JqZWN0IGZyb20gSnNvblJlYWRlci4gUGF0aCAnJywgbGluZSAxLCBwb3NpdGlvbiAxOTQ2LlxyXG4gICBhdCBOZXd0b25zb2Z0Lkpzb24uTGlucS5KT2JqZWN0LkxvYWQoSnNvblJlYWRlciByZWFkZXIsIEpzb25Mb2FkU2V0dGluZ3Mgc2V0dGluZ3MpXHJcbiAgIGF0IE5ld3RvbnNvZnQuSnNvbi5MaW5xLkpPYmplY3QuUGFyc2UoU3RyaW5nIGpzb24sIEpzb25Mb2FkU2V0dGluZ3Mgc2V0dGluZ3MpXHJcbiAgIGF0IEhhc2VsVHdlYWtzLkNvbmZpZ3VyYXRpb24uTG9hZChTdHJpbmdbXSB0d2Vha05hbWVzKSBpbiAvaG9tZS9ydW5uZXIvd29yay9IYXNlbFR3ZWFrcy9IYXNlbFR3ZWFrcy9Db25maWd1cmF0aW9uLmNzOmxpbmUgNDRcclxuICAgYXQgSGFzZWxUd2Vha3MuUGx1Z2luLi5jdG9yKERhbGFtdWRQbHVnaW5JbnRlcmZhY2UgcGx1Z2luSW50ZXJmYWNlKSBpbiAvaG9tZS9ydW5uZXIvd29yay9IYXNlbFR3ZWFrcy9IYXNlbFR3ZWFrcy9QbHVnaW4uY3M6bGluZSA0NVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlJ1bnRpbWVNZXRob2RIYW5kbGUuSW52b2tlTWV0aG9kKE9iamVjdCB0YXJnZXQsIE9iamVjdFtdIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBjb25zdHJ1Y3RvciwgQm9vbGVhbiB3cmFwRXhjZXB0aW9ucylcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZUNvbnN0cnVjdG9ySW5mby5JbnZva2UoT2JqZWN0IG9iaiwgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIsIEJpbmRlciBiaW5kZXIsIE9iamVjdFtdIHBhcmFtZXRlcnMsIEN1bHR1cmVJbmZvIGN1bHR1cmUpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLk1ldGhvZEJhc2UuSW52b2tlKE9iamVjdCBvYmosIE9iamVjdFtdIHBhcmFtZXRlcnMpXHJcbiAgIGF0IERhbGFtdWQuSW9DLkludGVybmFsLlNlcnZpY2VDb250YWluZXIuQ3JlYXRlQXN5bmMoVHlwZSBvYmplY3RUeXBlLCBPYmplY3RbXSBzY29wZWRPYmplY3RzKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJb0NcXEludGVybmFsXFxTZXJ2aWNlQ29udGFpbmVyLmNzOmxpbmUgMTA0XHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlR5cGVzLkxvY2FsUGx1Z2luLkxvYWRBc3luYyhQbHVnaW5Mb2FkUmVhc29uIHJlYXNvbiwgQm9vbGVhbiByZWxvYWRpbmcpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFR5cGVzXFxMb2NhbFBsdWdpbi5jczpsaW5lIDQxNCIsIkNvbnRleHQiOiJbTE9DQUxQTFVHSU5dIEVycm9yIHdoaWxlIGxvYWRpbmcgSGFzZWxUd2Vha3MifQ==
2022-08-10 00:06:54.589 +01:00 [ERR] [LOCALPLUGIN] Error while loading HaselTweaks
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 1946.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at HaselTweaks.Configuration.Load(String[] tweakNames) in /home/runner/work/HaselTweaks/HaselTweaks/Configuration.cs:line 44
   at HaselTweaks.Plugin..ctor(DalamudPluginInterface pluginInterface) in /home/runner/work/HaselTweaks/HaselTweaks/Plugin.cs:line 45
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 414
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 746
2022-08-10 00:06:54.591 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0xMFQwMDowNjo1NC41OTA3NjkyKzAxOjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBOZXd0b25zb2Z0Lkpzb24uSnNvblJlYWRlckV4Y2VwdGlvbjogRXJyb3IgcmVhZGluZyBKT2JqZWN0IGZyb20gSnNvblJlYWRlci4gUGF0aCAnJywgbGluZSAxLCBwb3NpdGlvbiAxOTQ2LlxyXG4gICBhdCBOZXd0b25zb2Z0Lkpzb24uTGlucS5KT2JqZWN0LkxvYWQoSnNvblJlYWRlciByZWFkZXIsIEpzb25Mb2FkU2V0dGluZ3Mgc2V0dGluZ3MpXHJcbiAgIGF0IE5ld3RvbnNvZnQuSnNvbi5MaW5xLkpPYmplY3QuUGFyc2UoU3RyaW5nIGpzb24sIEpzb25Mb2FkU2V0dGluZ3Mgc2V0dGluZ3MpXHJcbiAgIGF0IEhhc2VsVHdlYWtzLkNvbmZpZ3VyYXRpb24uTG9hZChTdHJpbmdbXSB0d2Vha05hbWVzKSBpbiAvaG9tZS9ydW5uZXIvd29yay9IYXNlbFR3ZWFrcy9IYXNlbFR3ZWFrcy9Db25maWd1cmF0aW9uLmNzOmxpbmUgNDRcclxuICAgYXQgSGFzZWxUd2Vha3MuUGx1Z2luLi5jdG9yKERhbGFtdWRQbHVnaW5JbnRlcmZhY2UgcGx1Z2luSW50ZXJmYWNlKSBpbiAvaG9tZS9ydW5uZXIvd29yay9IYXNlbFR3ZWFrcy9IYXNlbFR3ZWFrcy9QbHVnaW4uY3M6bGluZSA0NVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlJ1bnRpbWVNZXRob2RIYW5kbGUuSW52b2tlTWV0aG9kKE9iamVjdCB0YXJnZXQsIE9iamVjdFtdIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBjb25zdHJ1Y3RvciwgQm9vbGVhbiB3cmFwRXhjZXB0aW9ucylcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZUNvbnN0cnVjdG9ySW5mby5JbnZva2UoT2JqZWN0IG9iaiwgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIsIEJpbmRlciBiaW5kZXIsIE9iamVjdFtdIHBhcmFtZXRlcnMsIEN1bHR1cmVJbmZvIGN1bHR1cmUpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLk1ldGhvZEJhc2UuSW52b2tlKE9iamVjdCBvYmosIE9iamVjdFtdIHBhcmFtZXRlcnMpXHJcbiAgIGF0IERhbGFtdWQuSW9DLkludGVybmFsLlNlcnZpY2VDb250YWluZXIuQ3JlYXRlQXN5bmMoVHlwZSBvYmplY3RUeXBlLCBPYmplY3RbXSBzY29wZWRPYmplY3RzKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJb0NcXEludGVybmFsXFxTZXJ2aWNlQ29udGFpbmVyLmNzOmxpbmUgMTA0XHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlR5cGVzLkxvY2FsUGx1Z2luLkxvYWRBc3luYyhQbHVnaW5Mb2FkUmVhc29uIHJlYXNvbiwgQm9vbGVhbiByZWxvYWRpbmcpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFR5cGVzXFxMb2NhbFBsdWdpbi5jczpsaW5lIDQxNFxyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5QbHVnaW5NYW5hZ2VyLkxvYWRQbHVnaW5Bc3luYyhGaWxlSW5mbyBkbGxGaWxlLCBMb2NhbFBsdWdpbk1hbmlmZXN0IG1hbmlmZXN0LCBQbHVnaW5Mb2FkUmVhc29uIHJlYXNvbiwgQm9vbGVhbiBpc0RldiwgQm9vbGVhbiBpc0Jvb3QsIEJvb2xlYW4gZG9Ob3RMb2FkKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxQbHVnaW5NYW5hZ2VyLmNzOmxpbmUgNzQ2XHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlBsdWdpbk1hbmFnZXIuSW5zdGFsbFBsdWdpbkFzeW5jKFJlbW90ZVBsdWdpbk1hbmlmZXN0IHJlcG9NYW5pZmVzdCwgQm9vbGVhbiB1c2VUZXN0aW5nLCBQbHVnaW5Mb2FkUmVhc29uIHJlYXNvbikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcUGx1Z2luTWFuYWdlci5jczpsaW5lIDY5OSIsIkNvbnRleHQiOiJbUExVR0lOV10gUGx1Z2luIGluc3RhbGxlciB0aHJldyBhbiB1bmV4cGVjdGVkIGVycm9yIn0=
2022-08-10 00:06:54.590 +01:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 1946.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at HaselTweaks.Configuration.Load(String[] tweakNames) in /home/runner/work/HaselTweaks/HaselTweaks/Configuration.cs:line 44
   at HaselTweaks.Plugin..ctor(DalamudPluginInterface pluginInterface) in /home/runner/work/HaselTweaks/HaselTweaks/Plugin.cs:line 45
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 414
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 746
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 699

**Comment by Haselnussbomber** [comment]
Interesting. Seems like the configuration file can't be loaded.
Could you try to move or remove `AppData\Roaming\XIVLauncher\pluginConfigs\HaselTweaks.json`, so it can create a new one?

**Comment by jmrs2603** [comment]
Perfect, that did it! Thanks for your help.
